### ISSUE TITLE
Quick Status check

### ISSUE THREAD

**Issue by f3nation** [F3-Nation/f3-nation-slack-bot#1]
Is there a way to hit the endpoint and get a simple 200 back. In a Cloud Run I built previously, built on Flask, I had this in main.py.

```
@app.route('/')
def status():
    return Response('Service is running.', 200)
```

If I just went to my browser and entered the root URL, I got a 200 and it tole me everything is fine. I don't know slack_bolt enough to know if this can be done. Or even if there's value in it. I'm just imagining if we have this app everywhere, it's be nice to have a quick check to see if it's running and rule out the app and GCP and focus on other stuff.

-Tackle

**Comment by evanpetzoldt** [comment]
Done!
